// File generated by FlutterFire CLI.
// ignore_for_file: type=lint
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        return macos;
      case TargetPlatform.windows:
        return windows;
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyCWoy82vfxDxx2J9ANTqI7PLHs-maJeg_8',
    appId: '1:370210909643:web:cd98d4e9f107528c499a4e',
    messagingSenderId: '370210909643',
    projectId: 'hear-learn',
    authDomain: 'hear-learn.firebaseapp.com',
    storageBucket: 'hear-learn.firebasestorage.app',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyCcdPjJeuqjnL3yNR0-YpJuzJbIay0rdnk',
    appId: '1:370210909643:android:164b73dbfc9188f1499a4e',
    messagingSenderId: '370210909643',
    projectId: 'hear-learn',
    storageBucket: 'hear-learn.firebasestorage.app',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyCC9jxUj1JFdS4jW1sYTRJCmFUil4tBOJM',
    appId: '1:370210909643:ios:5cc58307e5c64a1b499a4e',
    messagingSenderId: '370210909643',
    projectId: 'hear-learn',
    storageBucket: 'hear-learn.firebasestorage.app',
    iosBundleId: 'com.example.hearLearn1',
  );

  static const FirebaseOptions macos = FirebaseOptions(
    apiKey: 'AIzaSyCC9jxUj1JFdS4jW1sYTRJCmFUil4tBOJM',
    appId: '1:370210909643:ios:5cc58307e5c64a1b499a4e',
    messagingSenderId: '370210909643',
    projectId: 'hear-learn',
    storageBucket: 'hear-learn.firebasestorage.app',
    iosBundleId: 'com.example.hearLearn1',
  );

  static const FirebaseOptions windows = FirebaseOptions(
    apiKey: 'AIzaSyCWoy82vfxDxx2J9ANTqI7PLHs-maJeg_8',
    appId: '1:370210909643:web:6b94405a7c6cd9a8499a4e',
    messagingSenderId: '370210909643',
    projectId: 'hear-learn',
    authDomain: 'hear-learn.firebaseapp.com',
    storageBucket: 'hear-learn.firebasestorage.app',
  );
}
